shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

### plugins
[plugins]
[plugins.zsh-autosuggestions]
apply = ["defer"]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
apply = ["defer"]
github = "zsh-users/zsh-completions"

[plugins.fast-syntax-highlighting]
apply = ["defer"]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.git-open]
apply = ["defer"]
github = "paulirish/git-open"

[plugins.cd-gitroot]
apply = ["fpath", "defer"]
github = "mollifier/cd-gitroot"

[plugins.zsh-replace-multiple-dots]
apply = ["defer"]
github = "momo-lab/zsh-replace-multiple-dots"

[plugins.zeno]
apply = ["defer"]
github = "yuki-yano/zeno.zsh"
hooks.post = """
__zeno_keybind() {
  if [[ -n $ZENO_LOADED ]]; then
    bindkey ' '  zeno-auto-snippet
    bindkey '^i' zeno-completion
    bindkey '^m' zeno-auto-snippet-and-accept-line
  fi
}
zsh-defer __zeno_keybind
"""
hooks.pre = """
export ZENO_ENABLE_SOCK=1
export ZENO_COMPLETION_FALLBACK=expand-or-complete
"""

[plugins.zsh-autopair]
apply = ["defer"]
github = "hlissner/zsh-autopair"

[plugins.local-defer]
apply = ["defer"]
local = "~/.config/zsh/plugins/defer"
use = ["*.zsh"]

[plugins.local-sync]
apply = ["source"]
local = "~/.config/zsh/plugins/sync"
use = ["*.zsh"]

### completions
[plugins.local-completions]
apply = ["fpath"]
local = "~/.local/share/zsh/completions"
