version: "3"
tasks:
  update:
    desc: "sheldonを更新する"
    cmds:
      - task: lock
      - task: build
  lock:
    desc: "sheldonをロックする"
    cmds:
      - sheldon lock --reinstall
    sources:
      - ./config/zsh/plugins/defer/*
      - ./config/zsh/plugins/sync/*
  cache:
    desc: "sheldonのソースをキャッシュする"
    sources:
      - ./config/sheldon/plugins.toml
    cmds:
      - echo "#!/usr/bin/env zsh" > $XDG_CACHE_HOME/sheldon/sheldon.zsh
      - sheldon source >> $XDG_CACHE_HOME/sheldon/sheldon.zsh
  build:
    desc: "sheldonでzshソースを出力してzcompileする"
    cmds:
      - task: cache
      - task: compile
  clean:
    desc: "sheldonのキャッシュを削除する"
    cmds:
      - rm $XDG_CACHE_HOME/sheldon/sheldon.zsh
      - rm $XDG_CACHE_HOME/sheldon/sheldon.zwc
  compile:
    desc: "キャッシュされたsheldonのsourceをコンパイルする"
    sources:
      - $XDG_CACHE_HOME/sheldon/sheldon.zsh
    cmds:
      - zsh -c "zcompile $XDG_CACHE_HOME/sheldon/sheldon.zsh"
