name: Editorconfig-checker
on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.17
      - run: go install github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker@latest
      - run: editorconfig-checker
