name: lint

on:
  push:
    branches: [ main ]

jobs:
  lint-check:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: brew install shellcheck

    - name: Check Scripts
      run: shellcheck ${GITHUB_WORKSPACE}/scripts/*

    - name: Check Git Subcommands
      run: shellcheck ${GITHUB_WORKSPACE}/.config/git/subcommand
