name: macos

on:
  push:
    branches: [ main ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy the directory
      run: mkdir ${HOME}/dotfiles && cp -r ${GITHUB_WORKSPACE}/ ${HOME}/dotfiles/

    - name: Run init.sh
      run: make init

    - name: Setup macOS defaults config
      run: make macos

    # - name: Load .zshenv
    #   run: |
    #     zsh ~/.zshenv 2> error.log; cat error.log
    #     if [ -s error.log ]; then false; fi

    # - name: Load .zprofile
    #   run: |
    #     zsh ${ZDOTDIR}/.zprofile 2> error.log; cat error.log
    #     if [ -s error.log ]; then false; fi

    # - name: Load .zshrc
    #   run: |
    #     zsh ${ZDOTDIR}/.zshrc 2> error.log; cat error.log
    #     if [ -s error.log ]; then false; f
