name: macos

on:
  push:
    branches: [ master ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run init.sh
      run: ${GITHUB_WORKSPACE}/init.sh

    - name: Load .zshenv
      run: |
        zsh ~/.zshenv 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .zprofile
      run: |
        zsh ${ZDOTDIR}/.zprofile 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .zshrc
      run: |
        zsh ${ZDOTDIR}/.zshrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; f
    